package com.example.miaosha.dao;

import com.example.miaosha.dataobject.userPasswordDO;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface userPasswordDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Thu May 06 14:06:08 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Thu May 06 14:06:08 CST 2021
     */
    int insert(userPasswordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Thu May 06 14:06:08 CST 2021
     */
    int insertSelective(userPasswordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Thu May 06 14:06:08 CST 2021
     */
    userPasswordDO selectByPrimaryKey(Integer id);

//    通过userId进行查询
    userPasswordDO selectByUserId(Integer userId);




    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Thu May 06 14:06:08 CST 2021
     */
    int updateByPrimaryKeySelective(userPasswordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Thu May 06 14:06:08 CST 2021
     */
    int updateByPrimaryKey(userPasswordDO record);
}